version: '3.8'
services:
  db:
    image: mysql:8.0.32
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=url_db
      - MYSQL_ROOT_PASSWORD=lorenza
      - MYSQL_ROOT_USER=root
      - MYSQL_HOST=localhost
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: url-shortener
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: lorenza
      DB_NAME: url_db
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local